---
become_override: False
ocp_username: opentlc-mgr
silent: False

user_count_start: 1
# The last user number to start with when creating projects
user_count_end: "{{user_count_start|int + num_users|int}}"
instructor_mode: false

use_openshift_build: false
use_openshift_pipelines: true

pipeline_builder_image: quay.io/willbenton/simple-model-s2i:cached-pipeline-s2i
pipeline_notebook_repository: https://github.com/willb/fraud-notebooks
pipeline_notebook_list: 02-feature-engineering.ipynb,03-model-logistic-regression.ipynb